version: "3.5"

services:
  graphcms:
    build: .
    container_name: graphcms
    environment:
      - OCTOBER_MODE=local
      - OCTOBER_PORT=8081
      - OCTOBER_GRAPHQL_PORT=8080
      - PG_HOST=postgres
      - PG_USERNAME=graphcms
      - PG_DATABASE=graphcms
      - PG_PASSWORD=graphcms
      - PG_PORT=5432
      - PG_APPLICATION=graphcms
    depends_on:
      - postgres
    ports:
      - "8080:8080"
  postgres:
    image: postgres:11.8
    environment:
      - POSTGRES_USER=graphcms
      - POSTGRES_PASSWORD=graphcms
      - POSTGRES_DB=graphcms
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U graphcms"]
      interval: 10s
      timeout: 5s
      retries: 5