---
kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ template "configMapName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
{{ (include "commonLabels" .) | indent 4 }}
data:
{{ .Files.Get "config.yaml" | indent 2 }}
