# We expect to fill the data out via the load_secrets.sh file in the root of the helm chart
# This is expected to happen BEFORE calling helm template
# FOR SAFETY, THIS SHOULD ALWAYS HAPPEN OUTSIDE OF THE GIT REPO!
---

kind: Secret
apiVersion: v1
metadata:
  name: {{ template "deploymentName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
{{ (include "commonLabels" .) | indent 4 }}
type: Opaque
data:
{{ .Files.Get "secrets.yaml" | indent 2 }}