apiVersion: v1
kind: Service
metadata:
  name: {{ template "deploymentName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
{{ (include "commonLabels" .) | indent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: graphql
      protocol: TCP
      name: graphql
  selector:
    # Select all nodes in this call. We don't select on labels, such as version,
    # to avoid downtime in the case of upgrades
    app: {{ template "deploymentName" . }}